{% for widget in widgets %}
- !Widget
  id: {{widget.widget.id}}
  kind: "{{widget.widget.kind}}"
  title: "{{widget.widget.title}}"
  dashboard: "{{widget.widget.dashboard}}"
  slots:{% for slot_data in widget.slots.values() %}
  - !Slot 
    subtitle: "{{slot_data.subtitle}}"
    label: "{{slot_data.label}}"
    datasource_func: !DataSourceFunc
      func_name: "Specify datasource func"
      func_kwargs: {}
  {% endfor %}
{% endfor %}